export default [
  { label: "AC", triple: true },
  { label: "/", operation: true },
  { label: "7" },
  { label: "8" },
  { label: "9" },
  { label: "*", operation: true },
  { label: "4" },
  { label: "5" },
  { label: "6" },
  { label: "-", operation: true },
  { label: "1" },
  { label: "2" },
  { label: "3" },
  { label: "+", operation: true },
  { label: "0", double: true },
  { label: "." },
  { label: "=", operation: true },
];
